exampleSite/content/blog/markdown-syntax.md, exampleSite/content/blog/math-typesetting.md, exampleSite/content/blog/rich-content.md, layouts/blog/single.html, layouts/partials/math.html, src/styles/pages/post.styl, static/css/about.css, static/css/post.css, static/css/posts.css, static/css/tags.css
The following changes are made to enhance the current theme:
- Adding additional sample posts from Hugo md templates, including rich content, markdown syntax and math typesetting to test the current theme
- Add `math.html` and add that partial to `single.html` so users can enable katex in posts
- Update `post.styl` and `post.css` for footer (currently showing different colour of footer to the background, i.e. #ffffff)
- Beautify format of css files
Additional suggestions:
- Syntax highlight doesn't seem to work well (but I'm not sure how to change it)
- ExampleSite doesn't seem to reflect all the changes I made, e.g. katex works well in the main content but not the example site (which i assume is less of an issue?)
- There doesn't seem to have a good way of creating additional custom …
=> Additions to Codex Hugo Theme

README.md, content/_index.md, content/blog/how-to-use-codex.md
This addresses some user experience issues when adding the theme to a project. Without default content, nothing renders on the screen (BAD XP). 
To address this, I've added some default content. It's the same content that renders in the [`exampleSite`](https://github.com/jakewies/hugo-theme-codex/tree/master/exampleSite), except it includes on 1 blog post that I will use as documentation. Probably just a re-use of the README until some things are fleshed out.
=> feat: add default content

layouts/_default/baseof.html
I just realized that the generated static resources were using `.Permalink`, which appended the site's `baseUrl` in front. This would break Netlify previews as they use a different temporary baseUrl. 
The simple fix is to change to `.RelPermalink`, which churns out `/css/<name>.css` instead of `<baseUrl>/css/<name>.css`. Tested with my Netlify pipeline.
=> Use RelPermalink instead of Permalink

layouts/_default/baseof.html
We're currently using `{{ .Page.Title }}` for the website's title. The problem is this value will be empty for the home page.
Following [this article](https://harrycresswell.com/articles/hugo-seo-accurate-page-titles/), we can update the title to use a combination of `.Site.Title` and `.Title` (same as `.Page.Title`) in order to make it unique for every page.
=> Fix site's title to be more SEO friendly

assets/scss/partials/_post-list.scss, exampleSite/config.toml, layouts/_default/list.html, layouts/_default/single.html, layouts/taxonomy/tag.html
The dateFormat is currently a magic string in several templates. I think it's better to extract it as an user configurable parameter.
Also adding `@import` statements for `_post-list.scss`, not that necessary but it'll stop IDEs from complaining.
=> Make dateFormat configurable

assets/scss/pages/post.scss, assets/scss/partials/_colors.scss, assets/scss/partials/_typography.scss, exampleSite/config.toml, exampleSite/content/blog/markdown-syntax.md
- I noticed that several examples in the `Markdown Syntax Guide` page are broken. 
It turns out that starting from Hugu 0.60, [raw HTML are disabled by default](https://discourse.gohugo.io/t/raw-html-getting-omitted-in-0-60-0/22032/2). We can simply enable that in the example config.
After:
- Also I added some basic stylings to tables & blockquotes, feel free to help me make them look better 😆 
Before:
After:
=> Enable raw HTML by default

layouts/_default/single.html
- Load minified code (3kB vs 30kB)
- Add prism autoloader so that we get highlighting for languages we
use.
- Hardcode exact prism version.  Perhaps this is controversial, but it
saves a redirect for each request, shaving off 30ms on a fast
connection.
=> Change how prismjs is loaded.

assets/scss/_main.scss
After #10, `<footer>` is nested inside `<main>` so now there is a 3rem padding at the bottom of every page. This PR changes it to 1rem which is more reasonable (Fixing #58).
Before:
After:
=> Fix #58: excessing bottom padding

README.md, exampleSite/config.toml
I noticed a few gotchas that might trip up newcomers to the project, so I tried to make things as clear as possible:
- Changed the name of the theme in the installation instruction from `themes/codex` to `themes/hugo-theme-codex` to stay consistent
- Be explicit as to where the `exampleSite/config.toml` file is located
- The 1 mandatory line that needs to be addressed in `exampleSite/config.toml` has been moved to the very top
=> docs: Clean up README and config.toml

exampleSite/config.toml, layouts/partials/social-icons.html
This fixes the bug where the social icons don't appear on the demo page.
Now icons will use absolute URLs:
Also, I added a title to the exampleSite's config so that page titles will appear as `<page> | codex` instead of `<page> |`:
=> Fix relative icon issue + add title

assets/scss/partials/_social-icons.scss
Fixes https://github.com/jakewies/hugo-theme-codex/issues/60 by increasing padding and icon size, margins.
=> Conform icons to Google's mobile usability reqs

assets/scss/partials/_nav.scss
Fix an issue where if the burger menu is expanded and then the browser window is expanded, the standard navigation is pushed to far right of the window. The navigation items stay there until the browser window is shrunk down once again to show the burger menu.
=> Fix nav display error when expanding window with open burger.

CONTRIBUTING.md, package.json
Fixes https://github.com/jakewies/hugo-theme-codex/issues/69.
- Add a `yarn build:example` script, which triggers a one-time rebuild of the example site
- Document usage of `yarn build:example` in `CONTRIBUTING.md`
=> Include a build:example script

layouts/_default/baseof.html
With the `X-Content-Type-Options: "nosniff"` header set, stylesheet inclusions without the correct MIME type will be rejected by the browser.
=> layouts: add text/css MIME type to stylesheets

exampleSite/config.toml, layouts/_default/baseof.html
As discussed in #82 this adds correct support for the meta tags `twitter:creator` and `twitter:site`.
Exact details for why can be found here https://github.com/jakewies/hugo-theme-codex/issues/82#issue-657111646
It handles users not setting the new config values `twitterCreator` and `twitterSite` by falling back to the current behaviour of using `twitter` in both places.
It is imperfect, because it will only render meta tags if the config contains `twitter`. I think we can assume anyone wanting twitter metadata for creator and site will display the twitter link - therefore enabling this along the way.
Long term I would like to decouple meta tags from the social icons and introduce the ability to change them per post.
Not limited to the two twitter tags changed here.
Resolves #82
=> Twitter Meta Tags

layouts/partials/nav.html
Lighthouse reports that the aria-controls attribute has an invalid value[1]. This
patch resolves it, fixing the lighthouse score[2].
1: https://github.com/msfjarvis/msfjarvis.dev/suites/933117726/artifacts/11488586
2: https://github.com/msfjarvis/msfjarvis.dev/suites/933157898/artifacts/11489135
This leaves one final issue in the accessibility section, the contrast of the username
text on the main page.
=> nav: fix aria attributes

README.md
I needed to set `iconOrder` when I wanted to edit the order of social icons. I think this example is clearer.
=> use iconOrder when editing/stating desired icon order

README.md, exampleSite/config.toml
While the README was updated in #91 to use `iconOrder` instead of `iconTitles`, the example site config was left unchanged.
=> docs: Use iconOrder when stating desired icon order

layouts/_default/single.html
Previously, all posts had to show a date. If the `date:` attribute was removed from the md file, then something like "0000 Jan 01" would default. 
This is use for static pages that are not part of the blog structure, like a separate "about" or "contact" page.
=> Allow for omitting date on post

README.md, exampleSite/config.toml
This PR documents the `showPageTitleInTOC` site param introduced in #10. Let me know if anything has to be changed.
=> docs: Document showPageTitleInTOC in README.md and config.toml

layouts/_default/baseof.html, layouts/partials/favicon.html
#46
- Backwards compatible with previous implementation
- Consumers can define their own favicon in parital, depending on their
preference of render / source
=> Extract favicon into a partial

layouts/partials/social-icons.html
[rel="me"](https://indieweb.org/rel-me) is a commonly used way to show that that two websites or social media accounts are the same, and is used for authentication and proving site ownership in a variety of ways.
=> Add rel-me to social links

layouts/partials/browse-by-tag.html
When browsing bt tags, it shows links to tag without `/`. For example, when browsing the blog page, the link on the side shows `http://localhost:1313/tags/kubernetes` and gives me 404 error page.
In this PR, the link should show `http://localhost:1313/tags/kubernetes/`.
=> Fix browse-by-tag link

layouts/_default/_markup/render-link.html
As of now, clicking on links opens them in the same tab. This patch adds a markdown render hook to open links in a new tab. 
This only works on Hugo v0.62.0 and above.
[Relevant docs page](https://gohugo.io/getting-started/configuration-markup/#markdown-render-hooks)
=> layouts: Add markdown render hook to open links in new tab

layouts/partials/social-icons.html
The `<a>` tag of social icons had two `rel` attributes, which didn't work — only the first one was kept. Instead of using the `rel` attribute twice with different values, we want to use it once with two values.
=> fix(social-icons): "rel" attribute with multiple values in links

exampleSite/content/blog/rich-content.md
I noticed that `yarn develop` is failing based on an unreachable endpoint for the Instagram shortcode. 
```yarn run v1.22.5
$ hugo server -s ./exampleSite/
Start building sites …
ERROR 2020/11/21 23:21:22 Failed to get JSON resource "https://api.instagram.com/oembed/?url=https://www.instagram.com/p/BGvuInzyFAe/&amp;maxwidth=640&amp;omitscript=true": Failed to retrieve remote file: Bad Request
If you feel that this should not be logged as an ERROR, you can ignore it by adding this to your site config:
ignoreErrors = ["error-remote-getjson"]
Built in 766 ms
Error: Error building site: logged 1 error(s)
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/
```
After some light digging it appears that Instagram deprecated their API and this shortcode is broken …
=> Remove broken instagram_simple shortcode

layouts/_default/baseof.html, theme.toml
As per #166 but with bumped minimum version added as that PR is old but I think this should to be added ASAP as breaking on new Hugo installs.
On a default install of the theme into a new vanilla Hugo site the build fails with errors:
<pre><font color="#CC0000"><b>ERROR</b></font> 2021/07/20 10:19:05 render of &quot;taxonomy&quot; failed: <font color="#06989A"><b>&quot;/home/test/themes/hugo-theme-codex/layouts/_default/baseof.html:39:97&quot;</b></font>: execute of template failed: template: _default/list.html:39:97: executing &quot;_default/list.html&quot; at &lt;.MediaType.Suffix&gt;: can&apos;t evaluate field Suffix in type media.Type
<font color="#CC0000"><b>ERROR</b></font> 2021/07/20 10:19:05 render of &quot;taxonomy&quot; failed: <font …
=> Add FirstSuffix to MediaType for Hugo v0.82 and bump minimum version of Hugo to 0.82
